import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {BsFillMoonStarsFill}  from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai';
import profilepic from '../public/memoji3.png'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Daniel Munoz-lara Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/memoji3.png" />
      </Head>
      <main className='bg-white px-10'>
        <section className = "min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='font-helveticaNeue text-xl'>Daniel Munoz</h1>
            <ul className='flex items-center'>
              <li> 
                <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
                </li>
              <li>
                <a className='bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 text-white px-4 py-2 rounded-md' href="#">Resume</a>
              </li>
              
            </ul>
          </nav>
          <div className ="text-center p-10">
            <h2 className='text-5xl py-2 text-purple-500 font-medium'>Daniel Munoz-lara</h2>
            <h3 className='text-2xl py-2'>Student and Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>I am currently making this website and praying it wont break</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-500'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-indigo-500 via-purple-500 to-pink-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={profilepic} layout="fill" objectFit="cover"/>
          </div>
        </section>
      </main>
    </div>
  )
}
